### ISSUE TITLE
Implementation of python

### ISSUE THREAD

**Issue by u8621011** [anhskohbo/u-convert#4]
Great Job, Anh,

I am searching the encoding translation lib for Vietnamese which can
1. detect what encoding is using?  VNI /TCVN3/ VIQR
2. Translated them into unicode.

Do you know is there any lib in python to do that job?

I have saw your library can be the similar job i am looking for but unfortunately is implemented in php.
 :-( 

Ted

**Comment by anhskohbo** [comment]
Sorry, I don't know any other. But you can implement this lib, it's easy I think so.
