### ISSUE TITLE
UConvert không hoạt động

### ISSUE THREAD

**Issue by vohai2003** [anhskohbo/u-convert#5]
Em viết kiểu này mà không hiểu sao nó không chạy nơi...
![image](https://user-images.githubusercontent.com/63694226/87876020-47ffa080-c9ff-11ea-9b9d-940be3a41cc8.png)

**Comment by anhskohbo** [comment]
Bạn check lại code nhé, `UConvert::toUnicode` trả lại 1 string chứ ko tham chiếu.
`$textvar = UConvert::toUnicode(...)`
